[package]
name = "claws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.20.0"
pcap = "1.1.0"
pnet = "0.34.0"
